name: Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 70.37.72.51
        username: issacnitin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo apt install curl
          sudo apt-get install gcc g++ make
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt-get install -y nodejs

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 70.37.72.51
        username: issacnitin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/issacnitin/
          if [ -d "BlogEngine/" ] 
          then
              cd BlogEngine/
              git pull origin master
          else
              git clone https://github.com/issacnitin/BlogEngine.git
              cd BlogEngine/
          fi
          npm install
          npm run build
          sudo cp ./src/beerwithai.com.conf /etc/nginx/sites-available/
          sudo ln -s /etc/nginx/sites-available/example.com.conf /etc/nginx/sites-enabled/
          sudo systemctl restart nginx
          sudo nginx -t
