name: Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 70.37.72.51
        username: issacnitin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          whoami
          cd /home/issacnitin/
          rm -rf BlogEngine/
          git clone https://github.com/issacnitin/BlogEngine.git
          cd BlogEngine
          sudo apt-get install node
          npm install
          npm run build
          sudo cp ./src/beerwithai.com.conf /etc/nginx/sites-available/
          sudo nginx restart
