name: Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: "Build package"
      run: |
        npm install
        npm run build
    
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 70.37.72.51
        username: issacnitin
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/*"
        target: "beerwithai.com/"
        overwrite: true
        strip_components: 1

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 70.37.72.51
        username: issacnitin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~
          sudo cp ./beerwithai.com/src/beerwithai.com.conf /etc/nginx/sites-available/
          if test -f "/etc/nginx/sites-enabled/default"; then
              sudo rm /etc/nginx/sites-enabled/default
          fi
          if [ -L "/etc/nginx/sites-enabled/beerwithai.com.conf" ]; then
              sudo rm /etc/nginx/sites-enabled/beerwithai.com.conf
          fi
          sudo ln -s /etc/nginx/sites-available/beerwithai.com.conf /etc/nginx/sites-enabled/
          sudo systemctl restart nginx
          sudo nginx -t
