name: Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: "Build package"
      run: npm run build
    
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: build/
        remote: ~/beerwithai.com
        host: 70.37.72.51
        username: issacnitin
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 70.37.72.51
        username: issacnitin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~
          sudo cp ./beerwithai.com/src/beerwithai.com.conf /etc/nginx/sites-available/
          if test -f "/etc/nginx/sites-enabled/default"; then
              sudo rm /etc/nginx/sites-enabled/default
          fi
          sudo ln -s /etc/nginx/sites-available/beerwithai.com.conf /etc/nginx/sites-enabled/
          sudo systemctl restart nginx
          sudo nginx -t
