name: Release

on: 
  issues:
    types: [milestoned]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: "Build package"
      run: |
        npm install
        npm run build
    
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 104.44.140.6
        username: issacnitin
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/*, src/beerwithai.com.conf"
        target: "beerwithai.com/"
        overwrite: true
        strip_components: 1